### ISSUE TITLE
imsi catcher.py wont run simultaneously with scan-and-livemon

### ISSUE THREAD

**Issue by ghost** [Oros42/IMSI-catcher#42]
I am unable to get IMSI-catcher.py to run simultaneously with scan-and-livemon.

I am on ubuntu and I have tried both installation methods you recommend.

"grgsm_livemon" works and shows output.  I am using RTL-SDR

> sudo grgsm_livemon 
> sudo: unable to resolve host dog1853
> gr-osmosdr v0.1.4-98-gc653754d (0.1.5git) gnuradio 3.7.12git-295-ga0adcd33
> built-in source types: file osmosdr fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy soapy redpitaya 
> [INFO] [UHDlinux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_3.11.0.git-740-g3a58a5f0] 
> Using device #0 Realtek RTL2838UHIDIR SN: 00000001
> Found Rafael Micro R820T tuner
> [R82XX] PLL not locked!
> Exact sample rate is: 2000000.052982 Hz
> [R82XX] PLL not locked!

> ```
> `sudo python scan-and-livemon
> [sudo] password for dog: 
> Locating potential GSM base station frequencies (this can take a few minutes).
> Traceback (most recent call last):
>   File "scan-and-livemon", line 101, in <module>
>     main()
>   File "scan-and-livemon", line 78, in main
>     list = find_gsm_bases()
>   File "scan-and-livemon", line 25, in find_gsm_bases
>     (options, args) = scanner.argument_parser().parse_args()
> AttributeError: 'module' object has no attribute 'argument_parser'
> ```

> ```
> ``sudo python simple_IMSI-catcher.py
> sudo: unable to resolve host dog1853
> [sudo] password for dog: 
> Nb IMSI ; TMSI-1     ; TMSI-2     ; IMSI              ; country      ; brand      ; operator              ; MCC  ; MNC   ; LAC    ; CellId

```

**Comment by Keskebeu** [comment]
Thats because you have to black list the rtl you are using. If you have used in a different OS like Windows than its meant to use with windows.

So blacklist this device and it should work. 
+ another problem is that grgsm does not support frequencies higher than PCS1900 and lower than 800 meaning that anything above that like 2000mhz wont be supported. I have been using this software and its fairly easy to get imsis and everything else but everything has to be 2g otherwise nothing will show up.

This is meant for 2g frequencies really old by now. What you should is connect your phone to gsm only on android (so you dont have to cause trouble by jamming) and than you will see what is happenning.

Let me know

**Comment by Mortensv** [comment]
do you have to bkacklist it in windows or linux?

**Comment by Keskebeu** [comment]
Blacklist it on linux.

**Comment by FFY00** [comment]
```
sudo modprobe -r dvb_usb_rtl28xxu
```

Should do it.

**Comment by Keskebeu** [comment]
When ppl is not locked than you dont have any frequencies nearby. Or if you do, you have to play around with ppm and gain options. 

I could not pick up signal with rtl-sdr even by trying to set a ppm and gain, but with ettus b200 I was picking up everything. So check it out.
